AWSTemplateFormatVersion: 2010-09-09

Description: Deploys an s3 bucket that can be accessed by Deployment and EC2 role

Resources:
  ArtifactsS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: dulearning-app-mod-lab-example-starter-php-artifacts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ArtifactsS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref ArtifactsS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:ListBucket'
              - 's3:AbortMultipartUpload'
            Effect: Allow
            Resource:
              - !Sub arn:aws:s3:::${ArtifactsS3Bucket}
              - !Sub arn:aws:s3:::${ArtifactsS3Bucket}/*
            Principal:
              AWS:
                - '{{resolve:ssm:cicd-role-arn}}'

  IdentityProviderParameter:
    Type: AWS::SSM::Parameter
    Properties:
      DataType: text
      Description: The name of the s3 bucket created for the artifacts
      Name: dulearning-app-mod-lab-example-starter-php-artifacts-bucket
      Tier: Standard
      Type: String
      Value: !Ref ArtifactsS3Bucket