name: Deploy starter PHP cloud formation to AWS

on:
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v2

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::006021234249:role/cicd-role
          role-session-name: StarterPHPCFDeploy

      - name: Deploy static site to S3 bucket
        run: aws cloudformation deploy --template-file ./s3-artifacts-bucket.yaml --stack-name appmod-lab-example-starter-php-s3-artifacts-bucket
